# Funding options for InTime Widget
# This file is optional and can be configured later when you set up sponsorship

# github: [mathis0]
# patreon: username
# ko_fi: username
# custom: ['https://paypal.me/username']
